site_name: Writing a Snake game with Rust and ggez
site_url: https://geckoblu-games.github.io/snake-ggez/

theme: 
    name: windmill 

nav:
    - 'Introduction': index.md
    - 'Project setup': 00_projectsetup.md
    - 'Open a Window': 01_justawindow.md
    - 'Draw an Image': 02_drawanimage.md
    - 'Draw text': 03_drawtext.md
    - 'Input handling': 04_inputhandling.md
